### ISSUE TITLE
INIT Decompression & Install fails on WinXP and Win2003Srvr

### ISSUE THREAD

**Issue by askpatrickw** [wwivbbs/wwiv#145]
Download a build.
extract it to \wwiv
run init and it will look normal.
Close init and re-run it and it will appear as though it wants to clean install again.

If you look in \wwiv you will see 3 zip files still there. On successful installs this does not happen.
I am not sure what is being missed when the install fails, but it might be more than what we can see.

I can repro this on WinSrvr2003. I need to verify that this is what happens on Jingles WinXP box as well.

**When this is fixed also remove the NOTE: from the Win Install page**  
https://github.com/wwivbbs/wwiv/wiki/installwindows

**Comment by askpatrickw** [comment]
unzip.exe in the build will not run on WindowsXP (works on Win7)

Even with an install run on a win7 box zipped up and supplied to WinXP box, the init complains it can't find config. Config IS present... I think there is some pre-req missing or something was introduced that does not work on XP\Winsrvr 2003.

**Comment by askpatrickw** [comment]
More research on this today....

[15:53] <Peaboy> So I can see in the changes in build 957 that there is an addition of UniversalCRT_IncludePath in many files.... 
[15:53] <Peaboy> I looked that up... http://blogs.msdn.com/b/vcblog/archive/2015/03/03/introducing-the-universal-crt.aspx
[15:53] <Peaboy> "For Windows versions prior to Windows 10, the Universal CRT is distributed via Windows Update. There are Windows Update MSU packages for Windows Vista through Windows 8.1. "
[15:54] <Peaboy> If that logic follows that CRT was added to the build and is not optional then I thin yes... we either roll that back or drop Pre-Vista support.

**Comment by askpatrickw** [comment]
Build 936 which was believed to be from SF does work on Jingle's XP box.

**Comment by askpatrickw** [comment]
OK... 955 does work on WinSrvr 2003R2 32-bit. The unzip complains about not being 32bit, but init seems to install fine (no .zips int eh \wwiv) and then you can relaunch init without errors.

**Comment by wwiv** [comment]
https://github.com/wwivbbs/wwiv/commit/adca361bb4b964db7d85b6638f339b477b81f68f should fix the zip/unzip not being recognized as valid win32 binaries.

**Comment by wwiv** [comment]
I thought the problem could be in File::Exists, so I ran a release build of core_test.exe on XP.  Confirming my suspicions, core_test.exe fails on XP

[==========] Running 107 tests from 9 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from DataFileTest
[ RUN      ] DataFileTest.Read
datafile_test.cpp(48): error: Value of: datafile.number_of_records()
  Actual: 536870911
Expected: 2
[  FAILED  ] DataFileTest.Read (15 ms)
[ RUN      ] DataFileTest.Write
[       OK ] DataFileTest.Write (0 ms)
[ RUN      ] DataFileTest.Read_DoesNotExist
[       OK ] DataFileTest.Read_DoesNotExist (0 ms)
[----------] 3 tests from DataFileTest (15 ms total)

[----------] 8 tests from IniFileTest
[ RUN      ] IniFileTest.Single_GetValue
[       OK ] IniFileTest.Single_GetValue (0 ms)
[ RUN      ] IniFileTest.Single_GetValue_Comment
[       OK ] IniFileTest.Single_GetValue_Comment (0 ms)
[ RUN      ] IniFileTest.Single_GetNumericValue
[       OK ] IniFileTest.Single_GetNumericValue (0 ms)
[ RUN      ] IniFileTest.Single_GetBooleanValue
[       OK ] IniFileTest.Single_GetBooleanValue (0 ms)
[ RUN      ] IniFileTest.Reopen_GetValue
[       OK ] IniFileTest.Reopen_GetValue (0 ms)
[ RUN      ] IniFileTest.TwoSection_GetValue
[       OK ] IniFileTest.TwoSection_GetValue (0 ms)
[ RUN      ] IniFileTest.TwoSection_GetValue_OnlyInSecondary
[       OK ] IniFileTest.TwoSection_GetValue_OnlyInSecondary (0 ms)
[ RUN      ] IniFileTest.CommentAtStart
[       OK ] IniFileTest.CommentAtStart (0 ms)
[----------] 8 tests from IniFileTest (16 ms total)

[----------] 6 tests from OsTest
[ RUN      ] OsTest.WaitFor_PredicateTrue
[       OK ] OsTest.WaitFor_PredicateTrue (0 ms)
[ RUN      ] OsTest.WaitFor_PredicateFalse
[       OK ] OsTest.WaitFor_PredicateFalse (328 ms)
[ RUN      ] OsTest.SleepFor
[       OK ] OsTest.SleepFor (110 ms)
[ RUN      ] OsTest.EnvironmentVariable_Exists
[       OK ] OsTest.EnvironmentVariable_Exists (0 ms)
[ RUN      ] OsTest.EnvironmentVariable_DoesNotExist
[       OK ] OsTest.EnvironmentVariable_DoesNotExist (0 ms)
[ RUN      ] OsTest.SetEnvironmentVariable
[       OK ] OsTest.SetEnvironmentVariable (0 ms)
[----------] 6 tests from OsTest (438 ms total)

[----------] 1 test from ScopeExitTest
[ RUN      ] ScopeExitTest.Basic
[       OK ] ScopeExitTest.Basic (0 ms)
[----------] 1 test from ScopeExitTest (0 ms total)

[----------] 5 tests from StlTest
[ RUN      ] StlTest.Contains_VectorInts
[       OK ] StlTest.Contains_VectorInts (0 ms)
[ RUN      ] StlTest.Contains_VectorStrings
[       OK ] StlTest.Contains_VectorStrings (0 ms)
[ RUN      ] StlTest.Contains_MapStringInts
[       OK ] StlTest.Contains_MapStringInts (0 ms)
[ RUN      ] StlTest.Contains_MapStringStrings
[       OK ] StlTest.Contains_MapStringStrings (0 ms)
[ RUN      ] StlTest.Contains_MapIntInts
[       OK ] StlTest.Contains_MapIntInts (0 ms)
[----------] 5 tests from StlTest (0 ms total)

[----------] 37 tests from StringsTest
[ RUN      ] StringsTest.StripColors
[       OK ] StringsTest.StripColors (0 ms)
[ RUN      ] StringsTest.StringColors_CharStarVersion
[       OK ] StringsTest.StringColors_CharStarVersion (0 ms)
[ RUN      ] StringsTest.Properize
[       OK ] StringsTest.Properize (0 ms)
[ RUN      ] StringsTest.StringPrintf_Smoke
[       OK ] StringsTest.StringPrintf_Smoke (0 ms)
[ RUN      ] StringsTest.StrCat_Smoke
[       OK ] StringsTest.StrCat_Smoke (0 ms)
[ RUN      ] StringsTest.StrCat_AlphaNumeric
[       OK ] StringsTest.StrCat_AlphaNumeric (0 ms)
[ RUN      ] StringsTest.StringReplace_EntireString
[       OK ] StringsTest.StringReplace_EntireString (0 ms)
[ RUN      ] StringsTest.StringReplace_PartialString
[       OK ] StringsTest.StringReplace_PartialString (0 ms)
[ RUN      ] StringsTest.StringReplace_NotFound
[       OK ] StringsTest.StringReplace_NotFound (0 ms)
[ RUN      ] StringsTest.SplitString_Basic
[       OK ] StringsTest.SplitString_Basic (0 ms)
[ RUN      ] StringsTest.SplitString_BasicReturned
[       OK ] StringsTest.SplitString_BasicReturned (0 ms)
[ RUN      ] StringsTest.SplitString_ExtraSingleDelim
[       OK ] StringsTest.SplitString_ExtraSingleDelim (0 ms)
[ RUN      ] StringsTest.SplitString_TwoDelims
[       OK ] StringsTest.SplitString_TwoDelims (0 ms)
[ RUN      ] StringsTest.SplitString_TwoDelimsBackToBack
[       OK ] StringsTest.SplitString_TwoDelimsBackToBack (0 ms)
[ RUN      ] StringsTest.StringToShort
[       OK ] StringsTest.StringToShort (0 ms)
[ RUN      ] StringsTest.StringToUnsignedShort
[       OK ] StringsTest.StringToUnsignedShort (0 ms)
[ RUN      ] StringsTest.StringToChar
[       OK ] StringsTest.StringToChar (0 ms)
[ RUN      ] StringsTest.StringToUnsignedChar
[       OK ] StringsTest.StringToUnsignedChar (0 ms)
[ RUN      ] StringsTest.RemoveWhitespace_NoSpace
[       OK ] StringsTest.RemoveWhitespace_NoSpace (0 ms)
[ RUN      ] StringsTest.RemoveWhitespace_InnerSpace
[       OK ] StringsTest.RemoveWhitespace_InnerSpace (0 ms)
[ RUN      ] StringsTest.RemoveWhitespace_Trailing
[       OK ] StringsTest.RemoveWhitespace_Trailing (0 ms)
[ RUN      ] StringsTest.RemoveWhitespace_Leading
[       OK ] StringsTest.RemoveWhitespace_Leading (0 ms)
[ RUN      ] StringsTest.StartsWith
[       OK ] StringsTest.StartsWith (0 ms)
[ RUN      ] StringsTest.EndssWith
[       OK ] StringsTest.EndssWith (0 ms)
[ RUN      ] StringsTest.StringJustify_Left
[       OK ] StringsTest.StringJustify_Left (0 ms)
[ RUN      ] StringsTest.StringJustify_LeftOtherChar
[       OK ] StringsTest.StringJustify_LeftOtherChar (0 ms)
[ RUN      ] StringsTest.StringJustify_Right
[       OK ] StringsTest.StringJustify_Right (0 ms)
[ RUN      ] StringsTest.StringJustify_RightOtherChar
[       OK ] StringsTest.StringJustify_RightOtherChar (0 ms)
[ RUN      ] StringsTest.StringJustify_LongerString
[       OK ] StringsTest.StringJustify_LongerString (0 ms)
[ RUN      ] StringsTest.StringTrim
[       OK ] StringsTest.StringTrim (0 ms)
[ RUN      ] StringsTest.StringTrimBegin
[       OK ] StringsTest.StringTrimBegin (0 ms)
[ RUN      ] StringsTest.StringTrimEnd
[       OK ] StringsTest.StringTrimEnd (0 ms)
[ RUN      ] StringsTest.StringUpperCase
[       OK ] StringsTest.StringUpperCase (0 ms)
[ RUN      ] StringsTest.StringLowerCase
[       OK ] StringsTest.StringLowerCase (0 ms)
[ RUN      ] StringsTest.CharStr
[       OK ] StringsTest.CharStr (0 ms)
[ RUN      ] StringsTest.StringRemoveWhitespace
[       OK ] StringsTest.StringRemoveWhitespace (0 ms)
[ RUN      ] StringsTest.StringRemoveChar
[       OK ] StringsTest.StringRemoveChar (0 ms)
[----------] 37 tests from StringsTest (31 ms total)

[----------] 5 tests from TransactionTest
[ RUN      ] TransactionTest.Commit
[       OK ] TransactionTest.Commit (0 ms)
[ RUN      ] TransactionTest.Rollback
[       OK ] TransactionTest.Rollback (0 ms)
[ RUN      ] TransactionTest.Rollback_RolebackNull
[       OK ] TransactionTest.Rollback_RolebackNull (0 ms)
[ RUN      ] TransactionTest.Commit_RollbackNull
[       OK ] TransactionTest.Commit_RollbackNull (0 ms)
[ RUN      ] TransactionTest.Commit_CommitNull
[       OK ] TransactionTest.Commit_CommitNull (0 ms)
[----------] 5 tests from TransactionTest (0 ms total)

[----------] 28 tests from FileTest
[ RUN      ] FileTest.DoesNotExist
[       OK ] FileTest.DoesNotExist (0 ms)
[ RUN      ] FileTest.DoesNotExist_Static
[       OK ] FileTest.DoesNotExist_Static (0 ms)
[ RUN      ] FileTest.Exists
file_test.cpp(52): error: Value of: dne.Exists()
  Actual: false
Expected: true
C:\DOCUME~1\rushfan\LOCALS~1\Temp\FileTest_Exists.55e67d2f\newdir
[  FAILED  ] FileTest.Exists (0 ms)
[ RUN      ] FileTest.Exists_Static
file_test.cpp(61): error: Value of: File::Exists(dne.full_pathname())
  Actual: false
Expected: true
C:\DOCUME~1\rushfan\LOCALS~1\Temp\FileTest_Exists_Static.55e67d2f\newdir
[  FAILED  ] FileTest.Exists_Static (0 ms)
[ RUN      ] FileTest.Exists_TrailingSlash
file_test.cpp(71): error: Value of: File::Exists(path)
  Actual: false
Expected: true
C:\DOCUME~1\rushfan\LOCALS~1\Temp\FileTest_Exists_TrailingSlash.55e67d2f\newdir\

[  FAILED  ] FileTest.Exists_TrailingSlash (0 ms)
[ RUN      ] FileTest.Length_Open
file_test.cpp(80): error: Value of: file.GetLength()
  Actual: -1
Expected: kHelloWorld.size()
Which is: 11
[  FAILED  ] FileTest.Length_Open (0 ms)
[ RUN      ] FileTest.Length_NotOpen
file_test.cpp(88): error: Value of: file.GetLength()
  Actual: -1
Expected: kHelloWorld.size()
Which is: 11
[  FAILED  ] FileTest.Length_NotOpen (0 ms)
[ RUN      ] FileTest.IsDirectory_NotOpen
[       OK ] FileTest.IsDirectory_NotOpen (0 ms)
[ RUN      ] FileTest.IsDirectory_Open
[       OK ] FileTest.IsDirectory_Open (16 ms)
[ RUN      ] FileTest.LastWriteTime_NotOpen
file_test.cpp(116): error: Expected: (now) <= (file.last_write_time()), actual:
1441168687 vs 0
[  FAILED  ] FileTest.LastWriteTime_NotOpen (0 ms)
[ RUN      ] FileTest.LastWriteTime_Open
file_test.cpp(126): error: Expected: (now) <= (file.last_write_time()), actual:
1441168687 vs 0
[  FAILED  ] FileTest.LastWriteTime_Open (0 ms)
[ RUN      ] FileTest.Read
[       OK ] FileTest.Read (0 ms)
[ RUN      ] FileTest.GetName
[       OK ] FileTest.GetName (0 ms)
[ RUN      ] FileTest.GetParent
[       OK ] FileTest.GetParent (0 ms)
[ RUN      ] FileTest.EnsureTrailingSlash
[       OK ] FileTest.EnsureTrailingSlash (0 ms)
[ RUN      ] FileTest.CurrentDirectory
[       OK ] FileTest.CurrentDirectory (0 ms)
[ RUN      ] FileTest.SetCurrentDirectory
[       OK ] FileTest.SetCurrentDirectory (0 ms)
[ RUN      ] FileTest.MakeAbsolutePath_Relative
[       OK ] FileTest.MakeAbsolutePath_Relative (0 ms)
[ RUN      ] FileTest.MakeAbsolutePath_AlreadyAbsolute
[       OK ] FileTest.MakeAbsolutePath_AlreadyAbsolute (0 ms)
[ RUN      ] FileTest.IsAbsolute
[       OK ] FileTest.IsAbsolute (0 ms)
[ RUN      ] FileTest.IsRelative
[       OK ] FileTest.IsRelative (0 ms)
[ RUN      ] FileTest.RealPath_Same
[       OK ] FileTest.RealPath_Same (0 ms)
[ RUN      ] FileTest.RealPath_Different
[       OK ] FileTest.RealPath_Different (0 ms)
[ RUN      ] FileTest.mkdir
file_test.cpp(265): error: Value of: File::Exists(path)
  Actual: false
Expected: true
[  FAILED  ] FileTest.mkdir (0 ms)
[ RUN      ] FileTest.mkdirs
file_test.cpp(277): error: Value of: File::Exists(path)
  Actual: false
Expected: true
[  FAILED  ] FileTest.mkdirs (0 ms)
[ RUN      ] FileTest.Stream
[       OK ] FileTest.Stream (0 ms)
[ RUN      ] FileTest.IsOpen_Open
[       OK ] FileTest.IsOpen_Open (0 ms)
[ RUN      ] FileTest.IsOpen_NotOpen
[       OK ] FileTest.IsOpen_NotOpen (0 ms)
[----------] 28 tests from FileTest (62 ms total)

[----------] 14 tests from TextFileTest
[ RUN      ] TextFileTest.Constructor_SunnyCase
[       OK ] TextFileTest.Constructor_SunnyCase (0 ms)
[ RUN      ] TextFileTest.Constructor_Path_And_Name
[       OK ] TextFileTest.Constructor_Path_And_Name (0 ms)
[ RUN      ] TextFileTest.Append
[       OK ] TextFileTest.Append (0 ms)
[ RUN      ] TextFileTest.ReadLine_CA
[       OK ] TextFileTest.ReadLine_CA (0 ms)
[ RUN      ] TextFileTest.ReadLine_String
[       OK ] TextFileTest.ReadLine_String (0 ms)
[ RUN      ] TextFileTest.Write
[       OK ] TextFileTest.Write (16 ms)
[ RUN      ] TextFileTest.WriteFormatted
[       OK ] TextFileTest.WriteFormatted (0 ms)
[ RUN      ] TextFileTest.WriteChar
[       OK ] TextFileTest.WriteChar (0 ms)
[ RUN      ] TextFileTest.WriteBinary
[       OK ] TextFileTest.WriteBinary (0 ms)
[ RUN      ] TextFileTest.Close
[       OK ] TextFileTest.Close (0 ms)
[ RUN      ] TextFileTest.Close_SecondCloseReturnsFalse
[       OK ] TextFileTest.Close_SecondCloseReturnsFalse (15 ms)
[ RUN      ] TextFileTest.IsEOF
[       OK ] TextFileTest.IsEOF (0 ms)
[ RUN      ] TextFileTest.GetPosition
[       OK ] TextFileTest.GetPosition (0 ms)
[ RUN      ] TextFileTest.ReadFileIntoString
[       OK ] TextFileTest.ReadFileIntoString (0 ms)
[----------] 14 tests from TextFileTest (47 ms total)

[----------] Global test environment tear-down
[==========] 107 tests from 9 test cases ran. (609 ms total)
[  PASSED  ] 97 tests.
[  FAILED  ] 10 tests, listed below:
[  FAILED  ] DataFileTest.Read
[  FAILED  ] FileTest.Exists
[  FAILED  ] FileTest.Exists_Static
[  FAILED  ] FileTest.Exists_TrailingSlash
[  FAILED  ] FileTest.Length_Open
[  FAILED  ] FileTest.Length_NotOpen
[  FAILED  ] FileTest.LastWriteTime_NotOpen
[  FAILED  ] FileTest.LastWriteTime_Open
[  FAILED  ] FileTest.mkdir
[  FAILED  ] FileTest.mkdirs

10 FAILED TESTS

**Comment by wwiv** [comment]
Looks like it could be this:
https://connect.microsoft.com/VisualStudio/feedback/details/1600505/stat-not-working-on-windows-xp-using-v14-xp-platform-toolset-vs2015

No workaround given.

**Comment by wwiv** [comment]
Better bug:
https://connect.microsoft.com/VisualStudio/feedback/details/1557168/wstat64-returns-1-on-xp-always

**Comment by askpatrickw** [comment]
Your fix for unzip works on Winsrvrr2003.
but, the init still fails in the same. 
We'll just watch for a VS2015 update I guess.

**Comment by wwiv** [comment]
unzip is still borked, probably since it uses stat too.

example from 1565
C:\wwiv>unzip -l dloads\sysop\en-menus.zip
unzip:  cannot find either dloads/sysop/en-menus.zip or dloads/sysop/en-menus.zip.zip.

**Comment by wwiv** [comment]
depends on https://github.com/wwivbbs/wwiv/issues/214

**Comment by wwiv** [comment]
WWIV requires Win7 or later now.
